### ISSUE TITLE
Aspire Rotary 4th axis

### ISSUE THREAD

**Issue by Gabjohn1** [grblHAL/PostProcessors#3]
Is there a post processor for aspire that will work with teensy 4.1 / grblHAL to be able to wrap around the y axis. 
thank you!

**Comment by terjeio** [comment]
I do not think that a special post processor is needed for wrapping around the Y-axis. Wrapping Y-axis motions to a rotary axis (A, B or C) would require a post processor supporting 4 or more axes - IMO not too hard to add by editing the default grbl post processor.
FYI [ioSender](https://github.com/terjeio) has experimental support for wrapping Y motions to a rotary axis...

**Comment by Gabjohn1** [comment]
Thank you terjeio,
Here are a few options for PPs on my Vetric Aspire...
![PP Mgt](https://user-images.githubusercontent.com/126249708/228663876-a6d2817f-faed-4400-9706-9428c7bfaecb.jpg)
If I save my file with a *.gcode and run it in IO Sender then the bit moves in the Y directions and not the rotary A. (3d view in IO looks legit)  If I save with a *.tap file the Y stays stationary and seems to work but the 3d view in IOSender is just a straight line.  I saved with "GCode Wrap to A"  .  Sorry for the confusion, I just feel like I'm doing something wrong.
Any help is so appreciated!

**Comment by terjeio** [comment]
Did you edit the grbl PP (make a copy first and use that rotary jobs)?
From the [documentation](https://docs.vectric.com/docs/V10.5/VCarvePro/ENU/Help/form/post-processor-editing/index.html) it seems you have to add this line in the header:

`ROTARY_WRAP_Y=A`

also inverse time mode might have to be enabled, or you have to compile grblHAL with the rotary fix enabled:

`INVERSE_TIME_MODE="YES"`

The rotary fix can be enabled in the Web Builder here:

![image](https://user-images.githubusercontent.com/20260062/228741847-4fa4fc94-888f-4da2-ad72-1bbb91b7fb5b.png)

**Comment by Gabjohn1** [comment]
Yes,  that makes more sense. I will create/edit a pp. And compile the firmwareThanks!
