### ISSUE TITLE
Question for Fusion360 Postprocessor for deleting additional brackets in operations

### ISSUE THREAD

**Issue by einencool** [grblHAL/PostProcessors#4]
Hello Terje,

I've got a question, and maybe you are able to help me in this case.
When I make my G-Code in Fusion, I often duplicate some machinings and change them to other "elements".

But when I do so, in Fusion it will add "(2)" or (3) to the end of the Name from the operation..
![image](https://github.com/grblHAL/PostProcessors/assets/37541729/62eaf3b1-3efc-4704-b5b5-5117dc6f343b)

And when I generate the G-Code and open it in IO-Sender, then I'll get an error.
You said a while ago, that it's not a correct behaiviour and I have to check it, but also in the "CPS" File I can't change it, because normally the brackets should be erased...

Maybe you have a hint for me.
![image](https://github.com/grblHAL/PostProcessors/assets/37541729/6217c8ac-e01a-4503-9b33-1a7a6b0751f0)

![image](https://github.com/grblHAL/PostProcessors/assets/37541729/4466af0d-b554-44dc-8f48-70d6061c0a20)

BR.
Chris

**Comment by terjeio** [comment]
Have you raised this issue with Fusion support?

Both ioSender and the controller will correctly error out on such comments, from the NIST RS274NGC v3 specification:

**3.3.4 Comments and Messages**
Printable characters and white space inside parentheses is a comment. A left parenthesis always
starts a comment. The comment ends at the first right parenthesis found thereafter. Once a left
parenthesis is placed on a line, a matching right parenthesis must appear before the end of the line.
Comments may not be nested; _it is an error if a left parenthesis is found after the start of a
comment and before the end of the comment_.

**Comment by einencool** [comment]
I'll see what I can do in the fusion Forum.
Thought it would be a small change, and this issue only raises for me, when I use GrblHal.

Some other GCode Senders don't have this problem (Candle / Lasergrbl), but you mentioned it also last year, so I'll hope, I can find a way to fix this.
Have a nice day :-)

**Comment by einencool** [comment]
Often I use Candle to see, how long the Code needs to run on the machine, since Fusion 360 doesn't show the correct time because of the "personal use" restrictions. 

But it seems, that I have found the brackets issue.
Some years ago when I modified the Postprocessor I added the signs " °? " to be replaced. These two signs seems to make the problems. I deleted them and now it seems to work (for now :-) )

**Comment by terjeio** [comment]
> I deleted them and now it seems to work (for now :-) )

Great. FYI unlike GRBL grblHAL (by default) now  ignores "printable" real time commands such as `?`, `~` or `!` when part of a comment or a $-command and instead passes them on to the gcode and $ command parsers. So you should be ok as long as you stick with grblHAL ;-)
